### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by pt88520** [No-Trade-No-Life/Yuan#855]
### Describe the bug

渲染错误 Error: Assertion failed: data must be asc ordered by time, index=1, time=NaN, prev time=NaN
很抱歉，页面在渲染过程中发生了错误。
任何的渲染错误都是非预期的。
请将错误信息报告给 Yuan 的维护者，以便我们及时修复此问题。
Error: Assertion failed: data must be asc ordered by time, index=1, time=NaN, prev time=NaN
    at assert (https://y.ntnl.io/assets/index.2f007ab7.js:1429:948)
    at checkItemsAreOrdered (https://y.ntnl.io/assets/index.2f007ab7.js:1442:291233)
    at e1.setMarkers (https://y.ntnl.io/assets/index.2f007ab7.js:1442:295085)
    at https://y.ntnl.io/assets/index.2f007ab7.js:1442:322682
    at Rj (https://y.ntnl.io/assets/index.2f007ab7.js:44:27079)
    at Ik (https://y.ntnl.io/assets/index.2f007ab7.js:44:47457)
    at https://y.ntnl.io/assets/index.2f007ab7.js:44:45520
    at w1 (https://y.ntnl.io/assets/index.2f007ab7.js:29:1729)
    at MessagePort.P1 (https://y.ntnl.io/assets/index.2f007ab7.js:29:2141)

请将错误信息报告给 Yuan 的维护者，以便我们及时修复此问题。错误：断言失败：数据必须按时间、index=1、time=NaN、prev time=NaN 排序 at 断言 （https://y.ntnl.io/assets/index.2f007ab7.js:1429:948） 在 checkItemsAreOrdered （https://y.ntnl.io/assets/index.2f007ab7.js:1442:291233） 在 e1.setMarkers 处 （https://y.ntnl.io/assets/index.2f007ab7.js:1442:295085） 在 https://y.ntnl.io/assets/index.2f007ab7.js:1442:322682 在 Rj （https://y.ntnl.io/assets/index.2f007ab7.js:44:27079） 在 Ik （https://y.ntnl.io/assets/index.2f007ab7.js:44:47457） 在 https://y.ntnl.io/assets/index.2f007ab7.js:44:45520 在 W1 （https://y.ntnl.io/assets/index.2f007ab7.js:29:1729） 在 MessagePort.P1 （https://y.ntnl.io/assets/index.2f007ab7.js:29:2141）

### To Reproduce

1.无法登陆  ，2.无法看走势图

**Comment by zccz14** [comment]
请问是在什么场景下遇到的？（模型回测、账户回放、或者其他）

**Comment by pt88520** [comment]
我现在完全无法正常使用https://y.ntnl.io/，打开界面是空白的  右下角点登陆也无法显示任何东西  启动里的  login 也不行  界面完全无法恢复，只能启动copilot。。。。

**Comment by pt88520** [comment]
![bc3212c3be8fcb8013d7342863b1711](https://github.com/user-attachments/assets/60720c48-893a-4454-ad86-4612ae90f070)
![c7f966880946fdc1d5210aacf0e9e1d](https://github.com/user-attachments/assets/3d491469-bd04-4ef1-93dc-487ee62594ed)
![d53f3f202f6d314a0fc55217b1aa697](https://github.com/user-attachments/assets/39a3bb9b-b617-4723-92cd-8ab40c14f00c)

**Comment by zccz14** [comment]
明白你的意思，这是因为 Yuan 更新了一个概念叫 [发行版](https://www.ntnl.io/zh-Hans/docs/basics/what-is-workspace#%E5%8F%91%E8%A1%8C%E7%89%88) 
我们为了更广泛的场景，删减了很多默认的功能，如果你有需要的话，可以针对特定的功能给你配置一个默认的发行版。

**Comment by pt88520** [comment]
非常感谢您的回复，如果可以的话，能不能帮我 做个本地部署这个版本的 教程，我想要的 很简单&nbsp; &nbsp;就是 测试策略的可行性，效果，然后我自己 按照策略 手动交易。Copilot&nbsp; 是一个非常好的策略生成器。 可以的话&nbsp; 我想自己花钱使用自己的。
你们现在不更新了&nbsp; ，有点可惜





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zheng ***@***.***&gt;; 
发送时间: 2024年10月26日(星期六) 晚上9:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [No-Trade-No-Life/Yuan] bug: <title&gt; (Issue #855)














 
明白你的意思，这是因为 Yuan 更新了一个概念叫 发行版
 我们为了更广泛的场景，删减了很多默认的功能，如果你有需要的话，可以针对特定的功能给你配置一个默认的发行版。

**Comment by zccz14** [comment]
> 自己 按照策略 手动交易。Copilot&nbsp; 是一个非常好的策略生成器。 可以的话&nbsp; 我想自己花钱使用自己的。 你们现在不更新了&nbsp; ，有点可惜

你的意思是，你想自己部署一个 Copilot AIGC 策略生成器，然后走自己的选择的大模型的接口是吗？
我们的 Copilot 这个功能因为也是对接的 ChatGPT，最近没有在深入研究这个东西，可能账户欠费了，也没管它。

**Comment by pt88520** [comment]
非常感谢。我加了VX叫haolin，可不可以加一下你的VX&nbsp; 我有个策略&nbsp; XAUUSD的
，低周期15分钟&nbsp; &nbsp;高周期1小时， 能达到6W的收益。。。。haolin说 应该是BUG&nbsp; &nbsp;策略好像透视了，不知道行不行。我的VX是&nbsp; 15349973399.我给你我跑起来的源码:&nbsp; XAUUSD 15分钟&nbsp; &nbsp;XAUUSD&nbsp; 1小时&nbsp; 高低周期。
//-----------------------------------------------------------------------------------------------------
import { useParamOHLC, useSinglePosition, useCCI, useATR } from ***@***.***";


export default () =&gt; {
&nbsp; const { product_id, close: C, high, low } = useParamOHLC("低周期");
&nbsp; const { high: highDay, low: lowDay, close: closeDay } = useParamOHLC("高周期");
&nbsp; const idxDay = closeDay.length - 2;
&nbsp; const idx = C.length - 1;


&nbsp; const cciFast = useCCI(high, low, C, 18);
&nbsp; const cciSlow = useCCI(high, low, C, 54);
&nbsp; const { ATR: atr108 } = useATR(highDay, lowDay, closeDay, 108);


&nbsp; const 中心价位 = (highDay[idxDay] + lowDay[idxDay] + closeDay[idxDay]) / 3;
&nbsp; const 突破买入价 = highDay[idxDay] + 2 * 中心价位 - 2 * lowDay[idxDay];
&nbsp; const 观察卖出价 = 中心价位 + highDay[idxDay] - lowDay[idxDay];
&nbsp; const 反转卖出价 = 2 * 中心价位 - lowDay[idxDay];
&nbsp; const 反转买入价 = 2 * 中心价位 - highDay[idxDay];
&nbsp; const 观察买入价 = 中心价位 - (highDay[idxDay] - lowDay[idxDay]);
&nbsp; const 突破卖出价 = lowDay[idxDay] - 2 * (highDay[idxDay] - 中心价位);


&nbsp; const pL = useSinglePosition(product_id, PositionVariant.LONG);
&nbsp; const pS = useSinglePosition(product_id, PositionVariant.SHORT);


&nbsp; useEffect(() =&gt; {
&nbsp; &nbsp; if (idxDay < 108) return; // 确保ATR有足够的数据


&nbsp; &nbsp; if (pL.volume === 0 &amp;&amp; pS.volume === 0) {
&nbsp; &nbsp; &nbsp; if (cciFast[idx] &gt; 100 &amp;&amp; C[idx] &gt; 突破买入价) {
&nbsp; &nbsp; &nbsp; &nbsp; pL.setTargetVolume(1);
&nbsp; &nbsp; &nbsp; } else if (cciFast[idx] < -100 &amp;&amp; C[idx] < 突破卖出价) {
&nbsp; &nbsp; &nbsp; &nbsp; pS.setTargetVolume(1);
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }


&nbsp; &nbsp; if (pL.volume &gt; 0) {
&nbsp; &nbsp; &nbsp; if (C[idx] < 反转卖出价 || (cciFast[idx] < cciSlow[idx] &amp;&amp; C[idx] < pL.entryPrice - atr108[idxDay])) {
&nbsp; &nbsp; &nbsp; &nbsp; pL.setTargetVolume(0);
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }


&nbsp; &nbsp; if (pS.volume &gt; 0) {
&nbsp; &nbsp; &nbsp; if (C[idx] &gt; 反转买入价 || (cciFast[idx] &gt; cciSlow[idx] &amp;&amp; C[idx] &gt; pS.entryPrice + atr108[idxDay])) {
&nbsp; &nbsp; &nbsp; &nbsp; pS.setTargetVolume(0);
&nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; }
&nbsp; }, [idx, idxDay]);
};


//---------------------------------------------------------------------------------------------------------------------------------------

看一下这个策略是不是透视了？


------------------&nbsp;原始邮件&nbsp;------------------


发件人:                                                                                                                        "No-Trade-No-Life/Yuan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月26日(星期六) 晚上9:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [No-Trade-No-Life/Yuan] bug: <title&gt; (Issue #855)





 
明白你的意思，这是因为 Yuan 更新了一个概念叫 发行版
 我们为了更广泛的场景，删减了很多默认的功能，如果你有需要的话，可以针对特定的功能给你配置一个默认的发行版。
